[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "prague"

optimizer = true
optimizer_runs = 200

via_ir = true

snapshot_file = "tools/.gas-snapshot"

fork_block_number = 12345678

[profile.default.invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false

# Base Mainnet profile
[profile.base]
chain_id = 8453
src = "contracts"
out = "out"
libs = ["lib"]
evm_version = "prague"

# Base Sepolia testnet profile
[profile.base_sepolia]
chain_id = 84531
src = "contracts"
out = "out"
libs = ["lib"]
evm_version = "prague"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
